apiVersion: v1
kind: Service
metadata:
  name: {{ template "rancher.fullname" . }}
  labels:
    app: {{ template "rancher.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePorts.http))) }}
    nodePort: {{ .Values.service.nodePorts.http }}
    {{- end }}
  selector:
    app: {{ template "rancher.fullname" . }}
  type: "{{ .Values.service.type }}"
